Python 3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 1, in <module>
    r
NameError: name 'r' is not defined

123==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
213
213
a
<built-in function input>

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
dada
a
'dada'

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
435345
b
6

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
123123123
A
{'1', '2', '3'}

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
123123123
B
3
A
{'3', '1', '2'}
a
'123123123'
a.count(1)
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    a.count(1)
TypeError: count() argument 1 must be str, not int
count1
Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    count1
NameError: name 'count1' is not defined
a.count[1]
Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    a.count[1]
TypeError: 'builtin_function_or_method' object is not subscriptable
a.count(123123123)
Traceback (most recent call last):
  File "<pyshell#11>", line 1, in <module>
    a.count(123123123)
TypeError: count() argument 1 must be str, not int
a.count('1')
3
a.count(a[1])
3

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
1231231231
DIC={a}
DIC
{'1231231231'}
DIC
{'1231231231'}
a
'1231231231'
max(DIC.keys())]
SyntaxError: unmatched ']'
max(DIC.keys())
Traceback (most recent call last):
  File "<pyshell#19>", line 1, in <module>
    max(DIC.keys())
AttributeError: 'set' object has no attribute 'keys'

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
123123123
사용한 숫자는 {'1', '2', '3'}개

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
123123123
사용한 숫자는 3개
find()
Traceback (most recent call last):
  File "<pyshell#20>", line 1, in <module>
    find()
NameError: name 'find' is not defined

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
1231231231
사용한 숫자는 3개
가장 많이 입력한 숫자는 1

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
6
이름 나이 사용언어?
이름 나이 사용언어?
이름 나이 사용언어?
이름 나이 사용언어?
이름 나이 사용언어?
이름 나이 사용언어?

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
6
이름 나이 사용언어?a 24 c
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 6, in <module>
    if x2<=19:
TypeError: '<=' not supported between instances of 'str' and 'int'

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
6
이름 나이 사용언어?a 29 t
이름 나이 사용언어?c 18 Python
c
이름 나이 사용언어?d
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 5, in <module>
    x1,x2,x3=input('이름 나이 사용언어?').split()
ValueError: not enough values to unpack (expected 3, got 1)

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
'사과'
'사과'

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
문자열을 입력하시오사과
1번

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
문자열을 입력하시오5
0

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
문자열을 입력하시오배
2번

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
문자열을 입력하시오포도
3번

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
문자열을 입력하시오ㅗ폳
0
A=['a','b','c','d']
A.index(a)
Traceback (most recent call last):
  File "<pyshell#23>", line 1, in <module>
    A.index(a)
ValueError: 'ㅗ폳' is not in list
A.index('a')
0

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
ㅊㄷㄹ
Traceback (most recent call last):
  File "<pyshell#25>", line 1, in <module>
    ㅊㄷㄹ
NameError: name 'ᄎᄃᄅ' is not defined


==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
a
Traceback (most recent call last):
  File "<pyshell#27>", line 1, in <module>
    a
NameError: name 'a' is not defined

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
1
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 6, in <module>
    b=input(a,'별명?')
TypeError: input expected at most 1 argument, got 2

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
ㅊㅇㄷ
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 6, in <module>
    b=input(a,'별명?')
TypeError: input expected at most 1 argument, got 2

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
ㅇ
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 5, in <module>
    b=input(a,'별명?')
TypeError: input expected at most 1 argument, got 2

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
차두라''
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 5, in <module>
    b=input(a,'별명?')
TypeError: input expected at most 1 argument, got 2

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
ㅁㅇㅁ
ㅁㅇㅁ별명?ㅇㅇㅇ

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
이름ㅁㅇ
ㅁㅇ별명?ㅇㅇ
이름ㅁㅇ
ㅁㅇ별명?ㅇㅇ
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 8, in <module>
    print(a+'의 별명은',A.index(a+1))
TypeError: can only concatenate str (not "int") to str
>>> 
==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
이름ㅁㅇ
ㅁㅇ별명?ㅇㅇ
이름ㅁㅇ
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 6, in <module>
    print(a+'의 별명은',A.index(a+1))
TypeError: can only concatenate str (not "int") to str
>>> 
==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
이름ad
ad별명?dd
이름ad
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 6, in <module>
    print(str(a)+'의 별명은',A.index(a+1))
TypeError: can only concatenate str (not "int") to str
>>> 
==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
이름ad
ad별명?dd
이름ad
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 6, in <module>
    print(a,'별명은',A.index(a+1))
TypeError: can only concatenate str (not "int") to str
>>> 
==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
이름ad
ad별명?dd
이름ad
ad 별명은 dd
