Python 3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

==== RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py ===
a

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
{1} {0}
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 1, in <module>
    print('{1} {0}').format('coding','haru')
AttributeError: 'NoneType' object has no attribute 'format'

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
haru coding
print({1} {0}.format('coding','haru'))
SyntaxError: invalid syntax. Perhaps you forgot a comma?

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
내 이름은 popo야 내 나이는 14야

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
내 이름은 popo야 내 나이는 14야

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
0.100000

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
0.1

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
0.1000000

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
12.3456000

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
12.345600

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
7.23 111

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 1, in <module>
    print('{0} {1} {2}'.format('A','B'))
IndexError: Replacement index 2 out of range for positional args tuple

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
A B C
weather=sunny
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    weather=sunny
NameError: name 'sunny' is not defined
weather='sunny'
print('오늘 날씨는 {}!'.format(weather))
오늘 날씨는 sunny!

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
co
de
co+de=code


= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
1
2
1+2=12

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
1
2
1.0+2.0=3.0

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
10
20
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 3, in <module>
    print("{}*{}={}".format(n1,n2,n1*n2))
NameError: name 'n2' is not defined

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
10
20
10.0*20.0=200.0

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
구의 반지름5
{:.2f} 구의 부피> 392.699
5**3
125

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
구의 반지름5
523.60

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
구의 반지름5
구의 부피: 523.60

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
구의 반지름:5
구의 부피: 523.60
구의 겉넓이: 314.16

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
lion


= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
lion tiger

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
Lion tiger
a

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
Lion tiger
['Lion', 'tiger']

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
lion tiger
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 1, in <module>
    a,a1=input()
ValueError: too many values to unpack (expected 2)

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
a
b
a

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
lion
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 1, in <module>
    a,a1=input().split()
ValueError: not enough values to unpack (expected 2, got 1)


= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
lion tiger
lion

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
lion tiger
tiger liontiger

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
Chulsoo 15
Minho 18
Chulsoo age + Minho age = 33

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
I love you.
You love me.
I love you.You love me.

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
I love you.You love me.

I love you.You love me.



= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
I love you.
You love me.
I love you.You love me.

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
I love you.     
You love me.     
I love you.     You love me.     

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
I love you.     
You love me.    
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 3, in <module>
    print(a.rstip()+b.rstrip())
AttributeError: 'str' object has no attribute 'rstip'. Did you mean: 'rstrip'?

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
I love you.    
You love me.   
I love you.You love me.

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
Cat meow
Dog bow-wow
Cow moo
Cat sounds meow
Dog sounds bow-wow
Cow sounds moo

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
Cat meow
Dog bow-wow
Cow moo
Cat sounds meow.
Dog sounds bow-wow.
Cow sounds moo.

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
Jaewook
24
95.7382
I am Jaewook(IdNo.24). I got95.7382in my midterm exam.

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
Jaewook
24
95.7382
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 4, in <module>
    print("I am",a+'(IdNo.'+b+'). I got','{:f}'.format(c),'in my midterm exam.')
ValueError: Unknown format code 'f' for object of type 'str'

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
Jaewook
24
95.7382
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 3, in <module>
    c=int(input())
ValueError: invalid literal for int() with base 10: '95.7382'

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
Jaewook
24
95.7382
I am Jaewook(IdNo.24). I got 95.738200 in my midterm exam.

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
%10s

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
['pen':10]
print("['pen':10][20:10]")
['pen':10][20:10]

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
item          count          price          rate

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
item          count          price          rate
pen          20          100          50.5
note          5          95          35.3
eraser          110          97          14.2

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
 item          count          price          rate
  pen          20          100          50.5
 note          5          95          35.3
eraser          110          97          14.2

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
      item     count     price      rate
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 2, in <module>
    print('{:>10}'.format('pen')+'{:>10}'.format('20')+'{:>10}'.foramt('100')+'{:>10}'.format('50.5'))
AttributeError: 'str' object has no attribute 'foramt'. Did you mean: 'format'?

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
      item     count     price      rate
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 2, in <module>
    print('{:>10}'.format('pen')+'{:>10}'.format('20')+'{:>10}'.formatt('100')+'{:>10}'.format('50.5'))
AttributeError: 'str' object has no attribute 'formatt'. Did you mean: 'format'?

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
      item     count     price      rate
       pen        20       100      50.5
      note         5        95      35.3
    eraser       110        97      14.2

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
item           countprice     rate      
pen               20100       50.5      
note               595        35.3      
eraser           11097        14.2      

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
item      count     price     rate      
pen       20        100       50.5      
note      5         95        35.3      
eraser    110       97        14.2      

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
h

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
Traceback (most recent call last):
  File "C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py", line 1, in <module>
    print('코딩하루'[4])
IndexError: string index out of range

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
aei

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
kjihgfedcba

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
a
[1, 's', ' ', ';']

= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
a
['a', 1, 's', ' ', ';']
list
<class 'list'>
list(a)
['a', 1, 's', ' ', ';']
list
<class 'list'>
list_1=[1,2,3,4,5]
print(list_1)
[1, 2, 3, 4, 5]
list_2=input('1 2 3 4 5 입력>>').split()
1 2 3 4 5 입력>>1 2 3 4 5
print(list_2)
['1', '2', '3', '4', '5']
list=[]
list
[]
list_name=[None]*5
list_name
[None, None, None, None, None]
list_name=['awdwdawdsgtht','asdrgthgnhnryt']*10
list_name
['awdwdawdsgtht', 'asdrgthgnhnryt', 'awdwdawdsgtht', 'asdrgthgnhnryt', 'awdwdawdsgtht', 'asdrgthgnhnryt', 'awdwdawdsgtht', 'asdrgthgnhnryt', 'awdwdawdsgtht', 'asdrgthgnhnryt', 'awdwdawdsgtht', 'asdrgthgnhnryt', 'awdwdawdsgtht', 'asdrgthgnhnryt', 'awdwdawdsgtht', 'asdrgthgnhnryt', 'awdwdawdsgtht', 'asdrgthgnhnryt', 'awdwdawdsgtht', 'asdrgthgnhnryt']
list_1=['a','b','c','d','e']
list_1.append('a')
list_1
['a', 'b', 'c', 'd', 'e', 'a']
list_1.append('a'[1])
Traceback (most recent call last):
  File "<pyshell#29>", line 1, in <module>
    list_1.append('a'[1])
IndexError: string index out of range
list_1.append([1]'a')
SyntaxError: invalid syntax. Perhaps you forgot a comma?
list_1.insert([1]'a')
SyntaxError: invalid syntax. Perhaps you forgot a comma?
list_1.insert([1],'a')
Traceback (most recent call last):
  File "<pyshell#32>", line 1, in <module>
    list_1.insert([1],'a')
TypeError: 'list' object cannot be interpreted as an integer
list_1.insert(1,'a')
list_1
['a', 'a', 'b', 'c', 'd', 'e', 'a']
list_1.append(1,'a')
Traceback (most recent call last):
  File "<pyshell#35>", line 1, in <module>
    list_1.append(1,'a')
TypeError: list.append() takes exactly one argument (2 given)
list_1.remove('a')
list_1
['a', 'b', 'c', 'd', 'e', 'a']
list_1.pop('a')
Traceback (most recent call last):
  File "<pyshell#38>", line 1, in <module>
    list_1.pop('a')
TypeError: 'str' object cannot be interpreted as an integer
list_1.pop(1)
'b'
list_1
['a', 'c', 'd', 'e', 'a']
list_1
['a', 'c', 'd', 'e', 'a']
a=list=['code']
a
['code']
list
['code']
a=list['code']
Traceback (most recent call last):
  File "<pyshell#45>", line 1, in <module>
    a=list['code']
TypeError: list indices must be integers or slices, not str
a=list('code')
Traceback (most recent call last):
  File "<pyshell#46>", line 1, in <module>
    a=list('code')
TypeError: 'list' object is not callable
a
['code']
lsit
Traceback (most recent call last):
  File "<pyshell#48>", line 1, in <module>
    lsit
NameError: name 'lsit' is not defined
list_a=list('code')
Traceback (most recent call last):
  File "<pyshell#49>", line 1, in <module>
    list_a=list('code')
TypeError: 'list' object is not callable
a=list(code)
Traceback (most recent call last):
  File "<pyshell#50>", line 1, in <module>
    a=list(code)
NameError: name 'code' is not defined. Did you forget to import 'code'?
a=list('code')
Traceback (most recent call last):
  File "<pyshell#51>", line 1, in <module>
    a=list('code')
TypeError: 'list' object is not callable
a = list('code')
Traceback (most recent call last):
  File "<pyshell#52>", line 1, in <module>
    a = list('code')
TypeError: 'list' object is not callable
list=""
a = list('code')
Traceback (most recent call last):
  File "<pyshell#54>", line 1, in <module>
    a = list('code')
TypeError: 'str' object is not callable
a = ""
a = list('code')
Traceback (most recent call last):
  File "<pyshell#56>", line 1, in <module>
    a = list('code')
TypeError: 'str' object is not callable
a=list('code')
Traceback (most recent call last):
  File "<pyshell#57>", line 1, in <module>
    a=list('code')
TypeError: 'str' object is not callable
pyshell#57
Traceback (most recent call last):
  File "<pyshell#58>", line 1, in <module>
    pyshell#57
NameError: name 'pyshell' is not defined
a=list(2134)
Traceback (most recent call last):
  File "<pyshell#59>", line 1, in <module>
    a=list(2134)
TypeError: 'str' object is not callable
a=list[1234]
Traceback (most recent call last):
  File "<pyshell#60>", line 1, in <module>
    a=list[1234]
IndexError: string index out of range
a=list(123)
Traceback (most recent call last):
  File "<pyshell#61>", line 1, in <module>
    a=list(123)
TypeError: 'str' object is not callable
a='list'(213)
Traceback (most recent call last):
  File "<pyshell#62>", line 1, in <module>
    a='list'(213)
TypeError: 'str' object is not callable
>>> n= list("123")
Traceback (most recent call last):
  File "<pyshell#63>", line 1, in <module>
    n= list("123")
TypeError: 'str' object is not callable
>>> 
= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
>>> a
['a', 'b', 'c']
>>> a=list('abc')
>>> a
['a', 'b', 'c']
>>> a=list('code')
>>> a
['c', 'o', 'd', 'e']
>>> 
= RESTART: C:/Users/hlabc/AppData/Local/Programs/Python/Python313/test.py
>>> a=list('code')
>>> b=list('1234')
>>> b
['1', '2', '3', '4']
>>> b=list("1234")
>>> b
['1', '2', '3', '4']
>>> c=list('H E L L O')
>>> c
['H', ' ', 'E', ' ', 'L', ' ', 'L', ' ', 'O']
